name: Deploy to Staging

on:
  push:
    branches: [ staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Test server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.N_THJ_TEST_HOST }}
        username: ${{ secrets.N_THJ_TEST_USER }}
        key: ${{ secrets.N_THJ_TEST_KEY }}
        script: |
          cd ~/server/quests/
          git fetch origin
          git reset --hard origin/staging
